[package]
name = "rstrie"
version = "0.1.0"
authors = ["jmrepetti <jmrepetti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
